server:
  port: 7070
  servlet:
    context-path: /v0

spring:
  datasource:
  #Mysql config
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/malls?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    hikari:
      maximumPoolSize: 10
      idleTimeout: 600000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000
    dbcp2:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
